name: RoyaleElo
version: 1.0
main: org.caronte.Main
api-version: 1.20

softdepend: [PlaceholderAPI]

commands:
  elo:
    description: Ver estadísticas de Elo
  elotop:
    description: Ver top Elo
  royaleelo:
    description: Comandos administrativos de RoyaleElo

permissions:
  royaleelo.admin:
    description: Acceso administrativo a RoyaleElo
    default: op